Extend ShareActivity to wrap captured link into org link if possible
orgzly-revived/orgzly-android-revived pull request #323
Opened 2024-09-14 22:11 UTC by lingnand

This looks at the incoming intent data and wraps a link with title information into an org link.

2024-09-15 20:56 UTC, amberin commented
Nice!

2024-09-15 20:57 UTC, amberin approved these changes

2024-09-19 17:42 UTC, stefan2904 commented on app/src/main/java/com/orgzly/android/ui/share/ShareActivity.java
> +                    Pattern pattern = Pattern.compile("^[a-z]+:[^ ]+");
No veto from me, but is there a better way to check if the given data is a URL?

2025-01-08 22:55 UTC, amberin requested changes
I have made a PR to your branch suggesting a different way to recognize URLs: https://github.com/lingnand/orgzly-android-revived/pull/1

2025-01-09 14:11 UTC, amberin commented
@lingnand We should switch to java.net.URI, as you suggested elsewhere (and look out for URISyntaxException instead).

2025-01-13 23:29 UTC, amberin approved these changes

2025-01-13 23:30 UTC, amberin commented
Thank you for your first contribution, @lingnand!

2025-01-13 23:30 UTC, merged