Add auto-sync on suspend
orgzly-revived/orgzly-android-revived pull request #50
Opened 2023-10-29 16:14 UTC by Riyyi

Trigger auto-sync when the app becomes invisible to the user, ex: when navigating away or when locking the device.
This is useful if you don't have `Note updated or deleted` turned on and are using notebooks with multiple users.

2023-10-29 21:56 UTC, cbkerr requested changes
This seems very useful!

Are there any times a user would want to sync only on open or only on close? If not, should we combine this with the `syncOnResume` into something like `syncOnAppVisibilityChange`.

One case could have to do with wanting to avoid a sync conflict when opening the app but wanting to always write out changes automatically.

2023-10-29 21:56 UTC, cbkerr commented on app/src/main/java/com/orgzly/android/sync/AutoSync.kt
> +        APP_SUSPEND,
Longer, but I think we should keep the same tense as the other actions so it's easier to read the code
```suggestion
        APP_SUSPENDED,
```

2023-10-29 22:37 UTC, Riyyi commented
Your suggestion has been applied. I'm not sure of a use case or scenario where separate toggles would be preferred. Either is fine for me, I can change it to 1 toggle if this is preferred.

2023-10-29 23:22 UTC, cbkerr approved these changes
Maybe others can comment on whether to use 1 or 2 checkboxes but this looks great to me. Thanks!

2023-10-30 05:53 UTC, amberin commented
Personally, I would love separate toggles for resume and suspend. I suspect it varies a lot what works best, depending on how long a typical sync takes. In my case, I have many notebooks and use a slow syncing method (Git), so syncing takes time, and therefore syncing only upon suspend looks interesting to me.

I am just one user. But I believe auto-sync behavior is an area where users will appreciate configurability. And since this adds to the existing functionality, I think adding a new toggle to the existing ones would be sensible.

2023-11-01 16:39 UTC, amberin approved these changes

2023-11-01 16:40 UTC, merged

2023-11-01 16:40 UTC, amberin commented
Thank you for contributing! ❤️

2023-11-12 22:11 UTC, alensiljak commented
Wow, just saw this now. Can't wait to try it out.
Thank you!